### PR TITLE
Bump stm to support upcoming LTS-13

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @mainland

**Comment by domenkozar** [comment]
ping @mainland

**Comment by domenkozar** [comment]
ping

**Comment by zenhack** [comment]
@mainland ping? Build fails on GHC 8.6.x, but works fine after bumping the version bound.

**Comment by gwils** [comment]
As a hackage trustee, I have made a metadata revision to the latest version of ref-tf (0.4.0.1) to allow stm 2.5.
It would still be good to merge this pull request so that future versions have the more relaxed bound as well.

**Comment by mainland** [comment]
Merged, thanks!

**Pull request closed without merging**
